# Generated by Django 4.1.5 on 2023-01-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anemometers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemometer',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='anemometers.tag'),
        ),
        migrations.CreateModel(
            name='WindReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('anemometer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anemometers.anemometer')),
            ],
        ),
    ]
