# Generated by Django 4.1.5 on 2023-01-06 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anemometers', '0003_windreading_reading_time_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='windreading',
            options={'ordering': ['-reading_time']},
        ),
        migrations.AlterField(
            model_name='windreading',
            name='anemometer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wind_readings', to='anemometers.anemometer'),
        ),
    ]
