# Generated by Django 4.1.5 on 2023-01-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anemometers', '0004_alter_windreading_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemometer',
            name='tags',
            field=models.ManyToManyField(to='anemometers.tag'),
        ),
    ]
